ymca/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
	path('signup/', views.SignUp.as_view(), name='signup'),
	# path('events', views.all_events, name='list-events'),
	path('register/<event_id>', views.register_for_event, name='register'),
	path('drop/<event_id>', views.drop_event, name='drop'),
	path('create-event/', views.create_event, name='create-event'),
	path('create-event-form', views.display_event_form, name='create-event-form'),
    path('searched', views.searched, name="searched"),
	path('searched-event', views.searched_user, name="searched-event"),
	path('registered', views.registered, name="registered"),
	path('view-users', views.view_users, name="view-users"),
	path('deactivate/<username>', views.deactivate, name="deactivate"),
	path('searched-users', views.searched_users, name="searched-users"),
	path('delete/<event_id>', views.delete, name="delete"),
	path('member/<username>', views.member, name="member"),
	path('nonmember/<username>', views.nonmember, name="nonmember"),
	# path('YMCA-login/', views.login, name='login'),
	# path('<int:event_id>/', views.event_details, name='event_details'),
    # path('<int:event_id>/', views.event, name='event'),
    # path('<int:event_id>/description/', views.description, name='description'),
    # path('<int:event_id>/sign_up/', views.sign_up, name='sign_up'),
]

ymca/forms.py
from django import forms

class EventForm(forms.Form):
	event_name = forms.CharField(label='Event Name', max_length=100)
	start_date = forms.DateField()
	end_date = forms.DateField()
	start_time = forms.TimeField()
	end_time = forms.TimeField()
	slots = forms.IntegerField(label='Max Slots')
	requirements = forms.CharField(required=False, label='Requirements', max_length=200, initial="-")
	recurring = forms.MultipleChoiceField(required=True, initial=1, widget=forms.CheckboxSelectMultiple,
		choices=(
			(1, "Monday"),
			(2, "Tuesday"),
			(3, "Wednesday"),
			(4, "Thursday"),
			(5, "Friday"),
			(6, "Saturday"),
			(7, "Sunday")
		)
	)
	non_member_cost = forms.IntegerField()
	member_cost = forms.IntegerField()
	location = forms.CharField(max_length=200)
	description = forms.CharField(required=False, max_length=200, initial="-")

ymca/templates/ymca/create-event.html
<!DOCTYPE html>
<html>
	<head>
		<style>
			input{
				margin: auto;
				display: block;
			}
			label{
				margin: auto;
				
			}
			div{
				margin: auto;
				  width: 25%;
				text-align: center;
			}
			#id_recurring{
				width: 100%;
				text-align: center;
			}
			#holder{
				border: 1px solid black;
				background-color: white;
			}
			body{
				background-color: gray;
			}
		</style>
		<title>YMCA Create Event</title>
	</head>
	<body>
		<div id="holder">
			<form action="{% url 'create-event' %}" method="POST">
		  		{% csrf_token %}
		   	 	{{ form }}
		   	 	<input type="submit" value="Submit">
			</form>
			<form action="{% url 'home' %}" id="login-form">
				<input type="submit" value="Back" />
			  </form>
		</div>
	</body>
</html>

ymca/templates/ymca/home.html
<html>

{% load auth_extras %}

  <head>
	{% load static %}
    <style>
     h1{
      color: black;
      text-align: center;
     }
	 form{
	   text-align: center;
	 }
	 #img{
		display: block;
  		margin-left: auto;
  		margin-right: auto;
  		width: 50%;
	 }
	 #buttonHolder{
		justify-content: center;
    	align-items: center;
		display: flex;
	 }
	.button{
		display: inline-block;
		padding-left: 5px;
		padding-right: 5px;
	}
	#allHolder{
		background-color: white;
		width: 75%;
		justify-content: center;
    	align-items: center;
		margin: auto;
		border: black 5px solid;
	}
	body{
		background-color: gray;
	}
	#events{
	 width: 50%;
	 margin: auto;
	}
	#eventWrapper{
		border: 1px black solid;
	}
	div{
		text-align: center;
	}
    </style>
  </head>
  <body>
	  <div id="allHolder">
	<img src="{% static 'pic/YMCAbanner.png' %}" alt="YMCA Logo" id="img">
	<h1>YMCA Programs Registration</h1>
    <h1>Welcome, {{ user.username|default:'Guest' }}</h1>
    <div>
		<div id="buttonHolder">
      {% if user.is_authenticated %}
		  <form action="{% url 'logout' %}" class="button">
		      <input type="submit" value="Log Out" />
		  </form>
		  {% if user.is_superuser %}
		  		<!-- <form action="http://127.0.0.1:8000/admin/ymca/event/add/">
					<input type="submit" value="Create Event" />
				</form> -->
				<form action="{% url 'create-event-form' %}" class="button">
					<input type="submit" value="Create Event" />
				</form>
				<form action="{% url 'view-users' %}" class="button">
					<input type="submit" value="View Users" />
				</form>
				<form action="{% url 'home' %}" id="login-form" class="button">
					<input type="submit" value="Home" />
				  </form>
		</div>
				<form action="{% url 'searched' %}">
					<input type="text" placeholder="Search Events by Username" name="search">
					<button type="submit">Go</button>
				  </form>
				 <form action="{% url 'searched-event' %}">
					<input type="text" placeholder="Search Events" name="search">
					<button type="submit">Go</button>
				  </form>
				<form action="{% url 'home' %}">
					<input type="submit" value="clear selection" />
				  </form>
		  {% else %}
				<form action="{% url 'registered' %}" class="button">
					<input type="submit" value="View Registed Events" />
					</form>
				<form action="{% url 'home' %}" class="button">
					<input type="submit" value="clear selection" />
				  </form>
		  {% endif %}

      {% else %}
		  <form action="{% url 'signup' %}" class="button">
		      <input type="submit" value="Sign Up" />
		  </form>
		  <form action="{% url 'login' %}" method="get" class="button">
		      <input type="submit" value="Log In" />
		  </form>
      {% endif %}
	  <a href="{% static "pic/YMCAUserManual.pdf" %}" style="border: black 1px solid; background-color: lightgray; color: black; font-weight: bold;">User Manual</a>
  </div>
  		<h1>Events</h1>

  <div class="container" id="events">
	  {% block content %}
				{% if messages %}
						<ul class="messages">
							{% for message in messages %}
								<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
							{% endfor %}
						</ul>
				{% endif %}
	  		{% if event_list %}
	  		{% for event in event_list %}
			<div id="eventWrapper">
			  <strong>{{ event }}</strong>
			<ul class="event">
				<li>Start: {{ event.start_date }}</li>
				<li>End: {{ event.end_date }}</li>
				<li>Days: {{ event.recurring }} </li>
				<li>Time: {{ event.start_time }} - {{ event.end_time }}</li>
				<li>Requirements: {{ event.requirements }}</li>
				<li>Slots: {{ event.taken_slots }}/{{ event.slots }}</li>
					{% if user.id|has_group:"member" or user.is_superuser == True or user.is_authenticated != True%}
					<li>Member Price: ${{ event.member_cost }}</li>
					{% endif%}
					{% if user.id|has_group:"member" != True or user.is_superuser == True or user.is_authenticated != True%}
					<li>Non-Member Price: ${{ event.non_member_cost }}</li>
					{% endif %}
				<li>Location: {{ event.location }}</li>
				<li>Info: {{ event.description }}</li>
				{% if user.is_authenticated and user.is_superuser != True%}
					<a href="{% url 'register' event.id %}">REGISTER</a>
					<a href="{% url 'drop' event.id %}">DROP</a>
				{% endif %}
				{% if user.is_superuser%}
				<a href="http://127.0.0.1:8000/admin/ymca/event/{{ event.id }}/change/">Modify Event</a>
				&emsp;
				<a href="{% url 'delete' event.id %}">Delete Event</a>
				{% endif %}
			</ul>
			
			{% endfor %}
			{% else %}
				<h1>NO EVENTS. . . COME BACK LATER</h1>
			{% endif %}
	  {% endblock %}
			</div>
  </div>
	  </div>
  </body>
</html>

ymca/templates/ymca/view_users.html
<html>

{% load auth_extras %}

  <head>
    <style>
     h1{
      color: black;
      text-align: center;
     }
	 form{
	   text-align: center;
	 }

    </style>
  </head>
  <body>
	<h1>YMCA</h1>
    <h1>User List</h1>
    <div>
      {% if user.is_authenticated %}
		  {% if user.is_superuser %}
				<form action="{% url 'home' %}">
					<input type="submit" value="HOME" />
				  </form>
				<form action="{% url 'searched-users' %}">
					<input type="text" placeholder="Search Users" name="search">
					<button type="submit">Go</button>
				  </form>
				<form action="{% url 'view-users' %}">
					<input type="submit" value="clear selection" />
				  </form>
		  {% else %}
		  {% endif %}

      {% else %}
      {% endif %}
  </div>
  		<h1>Users</h1>

  <div class="container" id="users">
	  {% block content %}
				{% if messages %}
						<ul class="messages">
							{% for message in messages %}
								<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
							{% endfor %}
						</ul>
				{% endif %}
	  		{% if user_list %}
	  		{% for users in user_list %}
			<strong>{{ users }}</strong>
			<ul class="class">
				<li>Username: {{ users.username }}</li>
				{% if user.is_superuser%}
					{% if users.is_active and users.is_superuser != True %}
					<a href="{% url 'deactivate' users.id %}">DEACTIVATE</a>
					{% endif%}
					{% if users.is_active != True and users.is_superuser != True %}
					<a href="{% url 'deactivate' users.id %}">ACTIVATE</a>
					{% endif %}
					&emsp;
					{% if users.id|has_group:"member" and users.is_superuser != True %} 
					<a href="{% url 'nonmember' users.id %}">Make nonmember</a>
					{% endif %}
					{% if users.id|has_group:"member" != True and users.is_superuser != True %} 
					<a href="{% url 'member' users.id %}">Make member</a>
					{% endif %}
				{% endif %}
			</ul>
			<hr style="width:18%;text-align:left;margin-left:0">
			<br>
			{% endfor %}
			{% else %}
				<h1>NO USERS. . . COME BACK LATER</h1>
			{% endif %}
	  {% endblock %}
  </div>

  </body>
</html>